"""Ground exploration enemy and stealth models.

Defines enemies with patrol routes, vision cones, and detection states.
Manages mission-level alert state, noise events, and enemy AI behavior.
"""

from __future__ import annotations

import math
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, TYPE_CHECKING

from spacegame.config import (
    GROUND_ALERT_DECAY_TURNS,
    GROUND_COMBAT_ENGAGE_RANGE,
    GROUND_DEFAULT_ENEMY_VISION,
    GROUND_ENEMY_VISION_CONE_ANGLE,
    GROUND_NOISE_NOISY_FLOOR,
    GROUND_SUSPICIOUS_DECAY_TURNS,
)
from spacegame.models.ground import (
    GroundInteractable,
    GroundMap,
    GroundPlayerState,
    GroundStoryTrigger,
    GroundTile,
    TileType,
)
from spacegame.models.ground_crew import GroundCrewBonuses

if TYPE_CHECKING:
    from spacegame.models.attributes import AttributeSheet
    from spacegame.models.progression import PlayerProgression


class Direction(Enum):
    """Cardinal facing direction for enemies."""

    UP = "up"
    DOWN = "down"
    LEFT = "left"
    RIGHT = "right"

    def to_delta(self) -> tuple[int, int]:
        """Convert direction to (dx, dy) movement delta."""
        return _DIRECTION_DELTAS[self]

    @classmethod
    def from_delta(cls, dx: int, dy: int) -> Optional[Direction]:
        """Get direction from a movement delta, or None if not cardinal.

        Args:
            dx: Horizontal delta.
            dy: Vertical delta.

        Returns:
            Direction if cardinal, None otherwise.
        """
        return _DELTA_TO_DIRECTION.get((dx, dy))

    def to_angle(self) -> float:
        """Get the angle in radians for this direction (0 = right, counter-clockwise)."""
        return _DIRECTION_ANGLES[self]


_DIRECTION_DELTAS: dict[Direction, tuple[int, int]] = {
    Direction.UP: (0, -1),
    Direction.DOWN: (0, 1),
    Direction.LEFT: (-1, 0),
    Direction.RIGHT: (1, 0),
}

_DELTA_TO_DIRECTION: dict[tuple[int, int], Direction] = {
    v: k for k, v in _DIRECTION_DELTAS.items()
}

_DIRECTION_ANGLES: dict[Direction, float] = {
    Direction.RIGHT: 0.0,
    Direction.UP: math.pi / 2,
    Direction.LEFT: math.pi,
    Direction.DOWN: -math.pi / 2,
}


class EnemyAIState(Enum):
    """Current behavior state of an enemy."""

    PATROLLING = "patrolling"
    INVESTIGATING = "investigating"
    SEARCHING = "searching"


class AlertLevel(Enum):
    """Mission-wide alert level."""

    UNDETECTED = "undetected"
    SUSPICIOUS = "suspicious"
    ALERT = "alert"
    COMBAT = "combat"


# Numeric ordering for alert level comparison
_ALERT_ORDER: dict[AlertLevel, int] = {
    AlertLevel.UNDETECTED: 0,
    AlertLevel.SUSPICIOUS: 1,
    AlertLevel.ALERT: 2,
    AlertLevel.COMBAT: 3,
}


@dataclass
class NoiseEvent:
    """A noise generated by the player or environment.

    Enemies within the radius will investigate.
    """

    x: int
    y: int
    radius: int


@dataclass
class GroundEnemy:
    """An enemy unit on the ground exploration map.

    Enemies have a position, facing direction, patrol route, vision cone,
    and AI state that governs their behavior each turn.
    """

    id: str
    x: int
    y: int
    facing: Direction = Direction.RIGHT
    vision_range: int = GROUND_DEFAULT_ENEMY_VISION
    speed: int = 1
    patrol_route: list[tuple[int, int]] = field(default_factory=list)
    patrol_index: int = 0
    ai_state: EnemyAIState = EnemyAIState.PATROLLING
    investigate_target: Optional[tuple[int, int]] = None
    loot_credits: int = 0
    template_id: str = "guild_security"

    def should_act(self, turn: int) -> bool:
        """Check if this enemy acts on the given turn based on speed.

        Args:
            turn: Current turn number.

        Returns:
            True if the enemy should act this turn.
        """
        if self.speed <= 0:
            return True
        if self.speed == 1:
            return True
        # Speed 2: act on even turns only
        return turn % self.speed == 0

    def can_see_tile(self, tx: int, ty: int, ground_map: GroundMap) -> bool:
        """Check if this enemy can see the given tile position.

        Considers vision range, vision cone angle, and line of sight.

        Args:
            tx: Target tile x.
            ty: Target tile y.
            ground_map: The map for LOS checks.

        Returns:
            True if the tile is visible to this enemy.
        """
        # Same tile is always visible
        if tx == self.x and ty == self.y:
            return True

        # Check distance (Chebyshev)
        dist = max(abs(tx - self.x), abs(ty - self.y))
        if dist > self.vision_range:
            return False

        # Check cone angle
        dx = tx - self.x
        dy = ty - self.y
        # Angle from enemy to target (note: y is inverted in screen coords)
        angle_to_target = math.atan2(-dy, dx)
        facing_angle = self.facing.to_angle()

        # Angle difference, normalized to [-pi, pi]
        diff = angle_to_target - facing_angle
        while diff > math.pi:
            diff -= 2 * math.pi
        while diff < -math.pi:
            diff += 2 * math.pi

        half_cone = math.radians(GROUND_ENEMY_VISION_CONE_ANGLE / 2)
        if abs(diff) > half_cone:
            return False

        # Check line of sight
        return ground_map.has_line_of_sight(self.x, self.y, tx, ty)

    def advance_patrol(self, ground_map: GroundMap) -> None:
        """Move to the next point on the patrol route.

        Updates position and facing direction. Wraps around at the end
        of the route.

        Args:
            ground_map: The map for walkability checks.
        """
        if not self.patrol_route:
            return

        # Advance to next point
        next_index = (self.patrol_index + 1) % len(self.patrol_route)
        next_x, next_y = self.patrol_route[next_index]

        # Update facing based on movement direction
        dx = next_x - self.x
        dy = next_y - self.y
        new_facing = Direction.from_delta(
            max(-1, min(1, dx)), max(-1, min(1, dy))
        )
        if new_facing is not None:
            self.facing = new_facing

        # Move if walkable
        if ground_map.is_walkable(next_x, next_y):
            self.x = next_x
            self.y = next_y
            self.patrol_index = next_index

    def move_toward(self, tx: int, ty: int, ground_map: GroundMap) -> None:
        """Move one step toward a target position.

        Tries the primary axis first, then the secondary axis if blocked.
        Updates facing direction.

        Args:
            tx: Target x.
            ty: Target y.
            ground_map: The map for walkability checks.
        """
        dx = tx - self.x
        dy = ty - self.y

        if dx == 0 and dy == 0:
            return

        # Try primary direction (larger delta first)
        moves: list[tuple[int, int]] = []
        if abs(dx) >= abs(dy):
            if dx != 0:
                moves.append((1 if dx > 0 else -1, 0))
            if dy != 0:
                moves.append((0, 1 if dy > 0 else -1))
        else:
            if dy != 0:
                moves.append((0, 1 if dy > 0 else -1))
            if dx != 0:
                moves.append((1 if dx > 0 else -1, 0))

        for mdx, mdy in moves:
            new_x = self.x + mdx
            new_y = self.y + mdy
            if ground_map.is_walkable(new_x, new_y):
                new_facing = Direction.from_delta(mdx, mdy)
                if new_facing is not None:
                    self.facing = new_facing
                self.x = new_x
                self.y = new_y
                return

    def to_dict(self) -> dict:
        """Serialize to dictionary."""
        data: dict = {
            "id": self.id,
            "x": self.x,
            "y": self.y,
            "facing": self.facing.value,
            "vision_range": self.vision_range,
            "speed": self.speed,
            "patrol_route": [list(p) for p in self.patrol_route],
            "patrol_index": self.patrol_index,
            "ai_state": self.ai_state.value,
            "loot_credits": self.loot_credits,
            "template_id": self.template_id,
        }
        if self.investigate_target is not None:
            data["investigate_target"] = list(self.investigate_target)
        return data

    @classmethod
    def from_dict(cls, data: dict) -> GroundEnemy:
        """Deserialize from dictionary.

        Args:
            data: Dictionary with enemy fields.

        Returns:
            GroundEnemy instance.
        """
        inv_target = data.get("investigate_target")
        return cls(
            id=data["id"],
            x=data["x"],
            y=data["y"],
            facing=Direction(data.get("facing", "right")),
            vision_range=data.get("vision_range", GROUND_DEFAULT_ENEMY_VISION),
            speed=data.get("speed", 1),
            patrol_route=[tuple(p) for p in data.get("patrol_route", [])],
            patrol_index=data.get("patrol_index", 0),
            ai_state=EnemyAIState(data.get("ai_state", "patrolling")),
            investigate_target=tuple(inv_target) if inv_target else None,
            loot_credits=data.get("loot_credits", 0),
            template_id=data.get("template_id", "guild_security"),
        )


@dataclass
class GroundMissionState:
    """Top-level state for an active ground exploration mission.

    Orchestrates enemies, alert level, noise processing, and turn management.
    """

    ground_map: GroundMap
    player: GroundPlayerState
    enemies: list[GroundEnemy] = field(default_factory=list)
    alert_level: AlertLevel = AlertLevel.UNDETECTED
    player_last_known_pos: Optional[tuple[int, int]] = None
    crew_bonuses: GroundCrewBonuses = field(default_factory=GroundCrewBonuses)
    attributes: Optional[AttributeSheet] = None
    progression: Optional[PlayerProgression] = None
    interactables: list[GroundInteractable] = field(default_factory=list)
    story_triggers: list[GroundStoryTrigger] = field(default_factory=list)
    _suspicious_turns_remaining: int = 0
    _alert_no_los_turns: int = 0
    _pending_noise: list[NoiseEvent] = field(default_factory=list)

    @property
    def effective_vision_radius(self) -> int:
        """Player vision radius including crew and attribute bonuses."""
        return self.player.vision_radius + self.crew_bonuses.vision_radius_bonus

    def get_interactable_at(self, x: int, y: int) -> Optional[GroundInteractable]:
        """Get an un-looted interactable at the given position.

        Args:
            x: Tile x coordinate.
            y: Tile y coordinate.

        Returns:
            The interactable, or None if nothing un-looted at that position.
        """
        for obj in self.interactables:
            if obj.x == x and obj.y == y and not obj.looted:
                return obj
        return None

    def get_story_trigger_at(self, x: int, y: int) -> Optional[GroundStoryTrigger]:
        """Get an un-triggered story trigger at the given position.

        Args:
            x: Tile x coordinate.
            y: Tile y coordinate.

        Returns:
            The story trigger, or None if nothing un-triggered at that position.
        """
        for trigger in self.story_triggers:
            if trigger.x == x and trigger.y == y and not trigger.triggered:
                return trigger
        return None

    def get_door_noise_radius(self) -> int:
        """Get the noise radius for opening a door, accounting for crew.

        Returns:
            0 if Marcus is present (silent doors), else GROUND_NOISE_DOOR_OPEN
            minus noise reduction.
        """
        if self.crew_bonuses.silent_doors:
            return 0
        from spacegame.config import GROUND_NOISE_DOOR_OPEN
        return max(0, GROUND_NOISE_DOOR_OPEN - self.crew_bonuses.noise_reduction)

    def get_revealed_patrol_tiles(self) -> set[tuple[int, int]]:
        """Get patrol route tiles to show when reveal_patrol_routes is active.

        Returns:
            Set of (x, y) tiles from all enemy patrol routes, or empty
            if patrol routes are not being revealed.
        """
        if not self.crew_bonuses.reveal_patrol_routes:
            return set()
        tiles: set[tuple[int, int]] = set()
        for enemy in self.enemies:
            for point in enemy.patrol_route:
                tiles.add(point)
        return tiles

    def calculate_loot_credits(self, base_credits: int) -> int:
        """Apply COM loot bonus to a base credit amount.

        COM // 2 * 10% bonus.

        Args:
            base_credits: Raw credit total before bonus.

        Returns:
            Credits after COM percentage bonus.
        """
        com_bonus_pct = 0.0
        if self.attributes:
            com = self.attributes.get_value("com")
            com_bonus_pct = (com // 2) * 0.10
        return int(base_credits * (1.0 + com_bonus_pct))

    def collect_enemy_loot(self, enemies: list[GroundEnemy]) -> int:
        """Sum loot credits from a list of enemies with COM bonus.

        Args:
            enemies: Enemies to collect loot from.

        Returns:
            Total credits after COM bonus.
        """
        base = sum(e.loot_credits for e in enemies)
        return self.calculate_loot_credits(base)

    def raise_alert(
        self,
        level: AlertLevel,
        investigate_pos: Optional[tuple[int, int]] = None,
    ) -> None:
        """Raise the alert level (never downgrades).

        Args:
            level: Target alert level.
            investigate_pos: Position to investigate (for SUSPICIOUS).
        """
        if _ALERT_ORDER[level] <= _ALERT_ORDER[self.alert_level]:
            # Don't downgrade, but do reset suspicious timer on re-trigger
            if level == AlertLevel.SUSPICIOUS and self.alert_level == AlertLevel.SUSPICIOUS:
                self._suspicious_turns_remaining = GROUND_SUSPICIOUS_DECAY_TURNS
                if investigate_pos:
                    self._set_enemies_investigating(investigate_pos)
            return

        self.alert_level = level

        if level == AlertLevel.SUSPICIOUS:
            self._suspicious_turns_remaining = GROUND_SUSPICIOUS_DECAY_TURNS
            if investigate_pos:
                self._set_enemies_investigating(investigate_pos)

        if level == AlertLevel.ALERT:
            self._alert_no_los_turns = 0
            self.player_last_known_pos = (self.player.x, self.player.y)
            for enemy in self.enemies:
                enemy.ai_state = EnemyAIState.SEARCHING

    def _set_enemies_investigating(self, pos: tuple[int, int]) -> None:
        """Set the nearest enemy to investigate a position.

        Args:
            pos: Position to investigate.
        """
        # Find nearest enemy that is patrolling
        best_enemy: Optional[GroundEnemy] = None
        best_dist = float("inf")
        for enemy in self.enemies:
            dist = abs(enemy.x - pos[0]) + abs(enemy.y - pos[1])
            if dist < best_dist:
                best_dist = dist
                best_enemy = enemy

        if best_enemy is not None:
            best_enemy.ai_state = EnemyAIState.INVESTIGATING
            best_enemy.investigate_target = pos

    def add_noise(self, noise: NoiseEvent) -> None:
        """Queue a noise event for processing.

        Args:
            noise: The noise event to add.
        """
        self._pending_noise.append(noise)

    def process_noise(self) -> None:
        """Process all pending noise events.

        Enemies within noise radius become INVESTIGATING and the
        alert level is raised to SUSPICIOUS.
        """
        for noise in self._pending_noise:
            alerted_any = False
            for enemy in self.enemies:
                dist = abs(enemy.x - noise.x) + abs(enemy.y - noise.y)
                if dist <= noise.radius:
                    enemy.ai_state = EnemyAIState.INVESTIGATING
                    enemy.investigate_target = (noise.x, noise.y)
                    alerted_any = True

            if alerted_any:
                self.raise_alert(
                    AlertLevel.SUSPICIOUS,
                    investigate_pos=(noise.x, noise.y),
                )

        self._pending_noise.clear()

    def check_tile_noise(self, x: int, y: int) -> Optional[NoiseEvent]:
        """Check if a tile generates noise when stepped on.

        Noise radius is reduced by crew bonuses (Tomas, ING attribute).

        Args:
            x: Tile x position.
            y: Tile y position.

        Returns:
            NoiseEvent if the tile is noisy, None otherwise.
        """
        tile = self.ground_map.get_tile(x, y)
        if tile is not None and tile.tile_type == TileType.NOISY_FLOOR:
            radius = max(
                0, GROUND_NOISE_NOISY_FLOOR - self.crew_bonuses.noise_reduction
            )
            return NoiseEvent(x=x, y=y, radius=radius)
        return None

    def check_enemy_vision(self) -> None:
        """Check if any enemy can see the player.

        If an enemy spots the player, raises alert to ALERT.
        """
        for enemy in self.enemies:
            if enemy.can_see_tile(self.player.x, self.player.y, self.ground_map):
                self.raise_alert(AlertLevel.ALERT)
                self.player_last_known_pos = (self.player.x, self.player.y)
                return

    def process_enemy_turns(self, turn_number: int) -> None:
        """Process all enemy actions for one turn.

        Handles patrol movement, investigation, searching, alert decay,
        and vision checks.

        Args:
            turn_number: Current turn number for speed calculations.
        """
        # Move enemies based on their AI state
        for enemy in self.enemies:
            if not enemy.should_act(turn_number):
                continue

            if enemy.ai_state == EnemyAIState.PATROLLING:
                enemy.advance_patrol(self.ground_map)

            elif enemy.ai_state == EnemyAIState.INVESTIGATING:
                if enemy.investigate_target is not None:
                    tx, ty = enemy.investigate_target
                    if enemy.x == tx and enemy.y == ty:
                        # Reached target, return to patrol
                        enemy.ai_state = EnemyAIState.PATROLLING
                        enemy.investigate_target = None
                    else:
                        enemy.move_toward(tx, ty, self.ground_map)

            elif enemy.ai_state == EnemyAIState.SEARCHING:
                if self.player_last_known_pos is not None:
                    enemy.move_toward(
                        self.player_last_known_pos[0],
                        self.player_last_known_pos[1],
                        self.ground_map,
                    )

        # Check if any enemy sees the player after moving
        self.check_enemy_vision()

        # Handle alert decay
        self._process_alert_decay()

    def _process_alert_decay(self) -> None:
        """Handle decay of alert levels over time."""
        if self.alert_level == AlertLevel.SUSPICIOUS:
            self._suspicious_turns_remaining -= 1
            if self._suspicious_turns_remaining <= 0:
                self.alert_level = AlertLevel.UNDETECTED
                for enemy in self.enemies:
                    if enemy.ai_state == EnemyAIState.INVESTIGATING:
                        enemy.ai_state = EnemyAIState.PATROLLING
                        enemy.investigate_target = None

        elif self.alert_level == AlertLevel.ALERT:
            # Check if any enemy can still see the player
            any_sees_player = any(
                enemy.can_see_tile(
                    self.player.x, self.player.y, self.ground_map
                )
                for enemy in self.enemies
            )

            if any_sees_player:
                self._alert_no_los_turns = 0
                self.player_last_known_pos = (self.player.x, self.player.y)
            else:
                self._alert_no_los_turns += 1
                if self._alert_no_los_turns >= GROUND_ALERT_DECAY_TURNS:
                    self.alert_level = AlertLevel.SUSPICIOUS
                    self._suspicious_turns_remaining = GROUND_SUSPICIOUS_DECAY_TURNS
                    for enemy in self.enemies:
                        enemy.ai_state = EnemyAIState.INVESTIGATING
                        enemy.investigate_target = self.player_last_known_pos

    def get_engaged_enemies(self) -> list[GroundEnemy]:
        """Get enemies within engagement range of the player.

        Returns:
            List of enemies within GROUND_COMBAT_ENGAGE_RANGE tiles.
        """
        engaged = []
        for enemy in self.enemies:
            dist = max(abs(enemy.x - self.player.x), abs(enemy.y - self.player.y))
            if dist <= GROUND_COMBAT_ENGAGE_RANGE:
                engaged.append(enemy)
        return engaged

    def to_dict(self) -> dict:
        """Serialize mission state to dictionary."""
        data: dict = {
            "ground_map": self.ground_map.to_dict(),
            "player": self.player.to_dict(),
            "enemies": [e.to_dict() for e in self.enemies],
            "alert_level": self.alert_level.value,
            "suspicious_turns_remaining": self._suspicious_turns_remaining,
            "alert_no_los_turns": self._alert_no_los_turns,
            "crew_bonuses": self.crew_bonuses.to_dict(),
        }
        if self.player_last_known_pos is not None:
            data["player_last_known_pos"] = list(self.player_last_known_pos)
        return data

    @classmethod
    def from_dict(cls, data: dict) -> GroundMissionState:
        """Deserialize mission state from dictionary.

        Args:
            data: Dictionary with mission state fields.

        Returns:
            GroundMissionState instance.
        """
        last_known = data.get("player_last_known_pos")
        crew_bonuses_data = data.get("crew_bonuses")
        crew_bonuses = (
            GroundCrewBonuses.from_dict(crew_bonuses_data)
            if crew_bonuses_data
            else GroundCrewBonuses()
        )
        mission = cls(
            ground_map=GroundMap.from_dict(data["ground_map"]),
            player=GroundPlayerState.from_dict(data["player"]),
            enemies=[GroundEnemy.from_dict(e) for e in data.get("enemies", [])],
            alert_level=AlertLevel(data.get("alert_level", "undetected")),
            player_last_known_pos=tuple(last_known) if last_known else None,
            crew_bonuses=crew_bonuses,
        )
        mission._suspicious_turns_remaining = data.get(
            "suspicious_turns_remaining", 0
        )
        mission._alert_no_los_turns = data.get("alert_no_los_turns", 0)
        return mission
