"""ROADMAP.md's index tables must agree with the sprint sections they summarise.

The roadmap's own instructions tell a human to "scan the index for arc-level
progress." Only the SA-arc table is auto-regenerated by the ralph harness; the
Followups and QF tables are hand-maintained and drift the moment a status
changes.

On 2026-08-24 that drift was total: all ten QF sprints and five of six
Followups read ``todo`` in the index while their sections read ``done``. The
index was not merely stale, it was actively misleading -- it caused a decision
to launch autonomous work against a backlog that was already finished, and the
resulting idle window went unnoticed for hours.

An index that lies is worse than no index, because people trust it. So the
agreement is enforced rather than documented.

Fix a failure with::

    python scripts/sync_roadmap_index.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[2]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.sync_roadmap_index import (  # noqa: E402
    ROADMAP_PATH,
    section_statuses,
    sync,
)


class TestRoadmapIndexInSync:
    def test_index_status_matches_sections(self) -> None:
        text = ROADMAP_PATH.read_text(encoding="utf-8")
        _new_text, drift = sync(text)
        assert not drift, (
            "ROADMAP.md index tables disagree with their sprint sections:\n  "
            + "\n  ".join(drift)
            + "\n\nRun: python scripts/sync_roadmap_index.py"
        )

    def test_scan_finds_sprints_at_both_heading_levels(self) -> None:
        """Guard against the scan silently matching nothing.

        Sprint headings are not uniform: the SA arc uses h4 (``#### SA-1 — ...``)
        because h3 is taken by its Phase groupings, while Followups and QF use
        h3 directly. CONVENTIONS.md documents only the h3 form. A scan written
        from the docs finds zero SA sprints and reports every SA index row as
        orphaned -- which is exactly what the first version of this checker did.
        """
        statuses = section_statuses(ROADMAP_PATH.read_text(encoding="utf-8"))
        assert any(k.startswith("SA-") for k in statuses), (
            "No SA-arc sprints found. The SA arc uses h4 headings; if the scan "
            "only matches h3 it will silently pass while checking nothing."
        )
        assert any(k.startswith("QF-") for k in statuses), (
            "No QF-arc sprints found. QF uses h3 headings."
        )

    @pytest.mark.parametrize("sprint_id", ["QF-1", "SA-F2", "CB-1"])
    def test_known_sprints_resolve_to_a_status(self, sprint_id: str) -> None:
        """Spot-check across all three heading/arc conventions in the file."""
        statuses = section_statuses(ROADMAP_PATH.read_text(encoding="utf-8"))
        assert sprint_id in statuses, (
            f"{sprint_id} has an index row but no resolvable section status."
        )
